IAERRLOGBN.SRVPGM: iaerrlogbn.bnd IAERRLOGRP.MODULE
IASRV02BN.SRVPGM: iasrv02bn.bnd IASRV02SV.MODULE
IASRV01BN.SRVPGM: iasrv01bn.bnd IASRV01SV.MODULE
IASRV03BN.SRVPGM: iasrv03bn.bnd IASRV03SV.MODULE
IADDSDDLSV.MODULE: iaddsddlsv.sqlrpgle
IADDSDDLBN.SRVPGM: iaddsddlbn.bnd IADDSDDLSV.MODULE
IAERRLOGRP.MODULE: iaerrlogrp.sqlrpgle
IAPCOD01BN.SRVPGM: iapcod01bn.bnd IAPCOD01SV.MODULE
IAGETKWDBN.SRVPGM: iagetkwdbn.bnd IAGETKWDSV.MODULE
IAGETKWDSV.MODULE: iagetkwdsv.sqlrpgle
IAPCOD02BN.SRVPGM: iapcod02bn.bnd IAPCOD02SV.MODULE
IAPCOD02SV.MODULE: iapcod02sv.sqlrpgle
IAVALIDTSV.MODULE: iavalidtsv.sqlrpgle
IAVALIDTBN.SRVPGM: iavalidtbn.bnd IAVALIDTSV.MODULE
IASRV03SV.MODULE: iasrv03sv.sqlrpgle
IAPCOD01SV.MODULE: iapcod01sv.sqlrpgle
IASRV01SV.MODULE: iasrv01sv.sqlrpgle